### ISSUE TITLE
Trap entities

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/roBrowserLegacy#50]
are missing.

Related to https://github.com/MrAntares/Ragna.roBrowser/issues/51

**Comment by MrAntares** [comment]
The entities are RSM models. Need to implement RSM effect handling.

Useful info:
ankle snare	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦01.rsm
skid trap	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦02.rsm
circle brown	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03.rsm
circle blue	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03_2.rsm
blast mine	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03_3.rsm
rectangle	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03_4.rsm
sprinkler	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03_5.rsm
shock	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦03_6.rsm
box	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦04.rsm
flat yellow	data\model\¿ÜºÎ¼ÒÇ°\Æ®·¦05.rsm


wines	data\model\event\3Â÷Æ®·¦_°¡½Ã01.rsm
blue skpiky circle	data\model\event\3Â÷Æ®·¦_º¯¼ö01.rsm
yellow spiky circle	data\model\event\3Â÷Æ®·¦_º¯Áö01.rsm
green	data\model\event\3Â÷Æ®·¦_º¯Ç³01.rsm
magenta	data\model\event\3Â÷Æ®·¦_º¯È­01.rsm
blue big square	data\model\event\3Â÷Æ®·¦_¼ö01.rsm
blue ufo	data\model\event\3Â÷Æ®·¦_Áö01.rsm
blue caterpillar	data\model\event\3Â÷Æ®·¦_Ç³01.rsm
volcano	data\model\event\3Â÷Æ®·¦_È­01.rsm

machine sound data\wav\effect\¹ÙÀÎµåÆ®·¦.wav

**Comment by issid** [comment]
https://github.com/MrAntares/roBrowserLegacy/pull/489 displays only the first trap, and cannot display several at once. requires improvement

**Comment by issid** [comment]
@MrAntares It seems this has been fixed and can be closed

**Comment by MrAntares** [comment]
There is still an issue if you place different traps. Their meshes get confuzed :/
